config:
  camera_index: 0
  port: 5052
  config_frame: true
  frame_height: 720
  frame_width: 1280
  display_video: true
  display_video_size: 1
  draw_pose: true
  static_mode: false
  max_hands: 1
  model_complexity: 1
  smooth_landmarks: true
  enable_segmentation: false
  smooth_segmentation: true
  min_detection_confidence: 0.5
  min_tracking_confidence: 0.5

output:
  include_fps: true
  include_height: false
  include_width: false
  flip_x: false
  flip_y: false
  lm_list: []
  include_box: false
  include_center: false
  include_visibility: true
  coordinates: "real"
  round: 2
  print_data: true